name: CI/CD Pipeline for Spring Boot & Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: 🛎️ Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java and Maven
      - name: 🏗️ Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Build the backend using Maven
      - name: 🏗️ Build backend
        run: |
          cd src
          mvn clean package -DskipTests

      # Step 4: Set up Node.js for frontend
      - name: 🏗️ Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: |
          cd whatsthis-frontend
          npm install
          npm run build

      # Step 5: Set up Docker Buildx
      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 6: Log in to Docker Hub
      - name: 🔑 Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Build and Push Backend Docker Image
      - name: 🏗️ Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: backend
          file: backend/Dockerfile
          push: true
          tags: ylmzunl/backend:latest

      # Step 8: Build and Push Frontend Docker Image
      - name: 🏗️ Build and Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: frontend
          file: frontend/Dockerfile
          push: true
          tags: ylmzunl/frontend:latest